--
-- PostgreSQL database dump
--

\restrict MlErO2eeADHI92ZdsLOL5XMct23PteaevqwdCsfr4gUrJ6lbZJwpMpSTRaaDxvq

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: order_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_item (
    id bigint NOT NULL,
    order_code character varying(30) NOT NULL,
    product_code character varying(15) NOT NULL,
    quantity bigint NOT NULL,
    price numeric(15,1)
);


ALTER TABLE public.order_item OWNER TO postgres;

--
-- Name: order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    code character varying(30) NOT NULL,
    total_price numeric(15,1),
    create_at timestamp with time zone DEFAULT now(),
    user_phone character varying(11) NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    code character varying(15) NOT NULL,
    name character varying(255) NOT NULL,
    remain integer NOT NULL,
    price numeric(15,1),
    search_vector tsvector GENERATED ALWAYS AS ((setweight(to_tsvector('simple'::regconfig, (COALESCE(name, ''::character varying))::text), 'A'::"char") || setweight(to_tsvector('simple'::regconfig, (COALESCE(code, ''::character varying))::text), 'B'::"char"))) STORED
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_users (
    id bigint NOT NULL,
    email character varying(50) NOT NULL,
    password text NOT NULL,
    role character varying(20),
    pin_hash character varying(255),
    pin_encrypted text,
    master_key_encrypted text
);


ALTER TABLE public.system_users OWNER TO postgres;

--
-- Name: system_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    user_name character varying(100) NOT NULL,
    address character varying(255) NOT NULL,
    image text NOT NULL,
    date_of_birth date NOT NULL,
    phone character varying(11) NOT NULL,
    card_id character varying(16) NOT NULL,
    public_key text NOT NULL,
    member_tier character varying(20) DEFAULT 'BRONZE'::character varying,
    quarter_spending numeric(15,1) DEFAULT 0.0,
    quarter_start_date date DEFAULT date_trunc('quarter'::text, (CURRENT_DATE)::timestamp with time zone),
    updated_at timestamp with time zone DEFAULT now(),
    gender character varying(5),
    balance bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_item (id, order_code, product_code, quantity, price) FROM stdin;
1	ORD-80a6def4	S251120000852	1	2000000.0
2	ORD-a37162bc	BBA251119164245	2	20000.0
3	ORD-32978a81	Á251125002114	1	1.0
4	ORD-a3a4b3e6	S251120000852	1	2000000.0
5	ORD-cf7aed22	BBA251119164245	1	10000.0
6	ORD-063ba776	S251120000852	1	2000000.0
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, code, total_price, create_at, user_phone) FROM stdin;
1	ORD-80a6def4	2000000.0	2025-12-17 20:55:02.576799+07	132456789
2	ORD-a37162bc	40000.0	2025-12-17 22:43:28.292315+07	132456789
3	ORD-32978a81	1.0	2025-12-17 22:46:45.529033+07	132456789
4	ORD-a3a4b3e6	2000000.0	2025-12-18 03:10:03.642002+07	12386783655
5	ORD-cf7aed22	10000.0	2025-12-18 03:11:21.369823+07	12386783655
6	ORD-063ba776	2000000.0	2025-12-18 07:36:17.496801+07	01267365578
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, code, name, remain, price) FROM stdin;
3	Á251125002114	áo	0	1.0
1	BBA251119164245	Bim bim abc	997	10000.0
2	S251120000852	Sweater-gucci	147	2000000.0
\.


--
-- Data for Name: system_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.system_users (id, email, password, role, pin_hash, pin_encrypted, master_key_encrypted) FROM stdin;
2	staff@gmail.com	$2a$12$DV9WMJxc6YsxZfpEfRUcluHgvlpzCPdI0UqHpCHQUqAYPIHC2oBFG	STAFF	\N	\N	\N
1	kienluu61@gmail.com	$2a$12$Mif0.NRiTAVwRmCefS8NaexvtJkguHZh9ekM0CCrYNt4Ps6VgpMPC	ADMIN	$2a$12$QoSIs5ooZfAecYL9VYn6qOsV3CRPGtF46zFZ8cj3wuuRA3L2./htW	r9Fs8j8+LWBqT5LHkf4rcj6g14yWdctI0Vs2YUjA69isfw==	wq9HzvWXn+tghli+aE51pTfy8K/2gQMbefn6dvWUiMnKuseRmqCUmmtw7/2XA5Q8wiztQTshxdFsDMyuO4LY0E8DVYhoZKKOrwZYZ/aQdEoBZKVNY4nPSqDlkTs=
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, user_name, address, image, date_of_birth, phone, card_id, public_key, member_tier, quarter_spending, quarter_start_date, updated_at, gender, balance) FROM stdin;
68	luu kiên	Hà Nội	http://res.cloudinary.com/dmi3xizxq/image/upload/nyzdimvnyk1pl3hjkuhl	2025-12-01	0123457689	4111117243842283	AICmjv/Na0ndG5FKwTKb2qgyUJ2V3e8hcXwE9mkzIna2l/8yLK9shwtq7GcZ5r+ZoWe9czoIAjd3GzyVrDXT0loPbetGyNV3C9T/RDnTRIoEeUSHSabAX02iCsyDWjfC2Azc+1FGeyTMbH8bdtwR+cr+bFximp5VOyzZ5LykfjJnQwADAQAB	BRONZE	0.0	2025-10-01	2025-12-18 01:23:21.148077+07	Nam	0
76	lưu đình kiên	Thanh Trì, Hà Nội	http://res.cloudinary.com/dmi3xizxq/image/upload/ygklpkwirnpgso0h7qyr	2025-12-01	01267365578	4111116287100251	AIDRRql5CiVTJ/50EkufqQutAKfDwXYD+Z/Kn7Uw1JXjgqsz1twqcymK8UjQFYNstO9aw/Tp0AFdsiP6p2N9+w+TKEF4iMqVTc9Tt92G8SdileeDTIel31QhMEtadBPML0HJwufPUQRYo4COTV3vnxjf2xvDaaQK4KHfn65iUm9nwwADAQAB	BRONZE	0.0	2025-10-01	2025-12-18 07:36:17.496801+07	Nam	998000000
4	lưu đình kiên	Bắc Ninh	http://res.cloudinary.com/dmi3xizxq/image/upload/qdqdergbdnxxbfmctwbh	2003-01-01	0123456789	9925224422367236	ca6423322006a54bf2a4da175a0299cc394cd5ef9b91ea435b58504d68aad4302e4c79a263aad158b082d9ce0fc8d93817b11f5012eb7032c5b639db692d4388ebc8f557f6df03d61cef432892b92944f8961b00b94a99330e9f05b3bf666f3cb5c9c50ca9679cf92fef98ce0bafc6da1e9492a53b0e2764f571bfe8cd68e825010001	BRONZE	0.0	2025-10-01	2025-11-25 21:57:16.217002+07	Nam	0
7	lưu kien	băc ninh	http://res.cloudinary.com/dmi3xizxq/image/upload/jmxqy8hfekwlmuhyc8lm	2003-01-01	0213456789	1979490006974767	d41f6b08acbd7c2f6f510244ae8298f8dc268c4c0c2aec2f6297f6d2e3c1f94604b5e67866394136e9d0d51142c559c77c5ef7dc392afa1051d4c0d4e90f409e4c63bcaa57a14045f6f9a7497f6a8bb0796fb5f4cb6f7a65780dc896021dc83120c3cb257c24455812c914ced435e6e16ff5837c9c1610937961836eb6990433010001	BRONZE	0.0	2025-10-01	2025-11-26 10:17:51.482652+07	Nam	0
8	lưu kien	ửe	http://res.cloudinary.com/dmi3xizxq/image/upload/bhtb7j4sh9uaxn9ncela	2003-01-01	032456789	6922985701857677	c0ac22860cee6cfd53efc476fbcff165c2972ae68889b59979aabceb7eab9f5880f3f45a544f6660a98811f1c6412576a627eeb2ffbbd9f890e591488d60fbe2e6c17b27dc95c2a2f5da7fb1faf148f618d6f08a26daaddd5181096987735d1357c000f3a402709784c49ef313a8d79a51e6c233c17265d55cf3ae67892a263b010001	BRONZE	0.0	2025-10-01	2025-11-26 10:18:58.366094+07	Nữ	0
9	đào thuý nga	Hà nội	http://res.cloudinary.com/dmi3xizxq/image/upload/ukepcdo3t9sos1ioqmem	2002-03-22	0865034796	1975657880150562	de2423942e7dd86915a99d49662a7ea155d033447619f516e6f1c2396b7fdab793a50e29849e223bd20e007fe5d8fc6b8f1cd54adc0fbb09ab06c3c712a2c1b8e3cab79f42e4f23b3f45b55111d0acca816be29f141446f08e49d06607abcb244410723b44c229e111c05bbb266ed1751a2eca5faad7c2230a401f667fba6af9010001	BRONZE	0.0	2025-10-01	2025-11-26 13:55:32.919758+07	Nữ	0
10	quy dat	Hà Nội	http://res.cloudinary.com/dmi3xizxq/image/upload/wonpdh3smpw1nmvgmloi	2003-10-27	02345678910	2157606054664782	d6e968c78279c677d52e96327dc0fe44960ddcbe61ebdd1fed794aad76cea4a52eddbd046b72dff4725f15c4bd5667a3c27a28732d3168a27ab3d3a3b90027ee4f3fc2a73980d8c5209e4cbcac163b1cea670dab097317603ce2ea1f3b8cdcbbf5e84690b46daa2c5dfafa8f8ec524c12fb659650c260d2027674eac3151b05d010001	BRONZE	0.0	2025-10-01	2025-11-26 15:18:58.60602+07	Nam	0
12	lưu	sdhtyj	http://res.cloudinary.com/dmi3xizxq/image/upload/r83fzsetj49jsoiapud7	2025-11-06	1243658889	1638737900215098	bbd3d9107a959299b387dd16f441828bf10ed6c11b8e1dca57a0d6b0df207be121555f1d467f08bda8712781ab9554927a6896bcf9dcf20ce41a48078f451772910ad2b0a80d53268155479205f9d36880f3e566b26e755c54b31f317b259853902f1cbabf479047c10f3f5093b7a638399ebd446af6787cc0645fdf5a102ef7010001	BRONZE	0.0	2025-10-01	2025-11-27 18:06:42.643488+07	Nam	0
13	lưu đình kiên	Bắc Ninh	http://res.cloudinary.com/dmi3xizxq/image/upload/ggmvuxpib0z8a1gkw7gd	2003-01-01	018398544	7303067107221787	b6f7ce5196863a9db315ae51edf1fa4869093401521fde9a31f20542ceaf1a32ca24c9fab4d477d84d7ab225219d941e66d2f9b3438d343b04de055574bb5a17d0e7f81d5a0ff4e23a84d77a8cbff6f21bcb80b6acf8633cb35e0a95f17de081cd9b617cb9fcd859a45cee381068e046a8dc179fb27230f031bd3653f3c190ff010001	BRONZE	0.0	2025-10-01	2025-12-01 22:05:48.458317+07	Nam	0
14	quy dat	Ha Noi	http://res.cloudinary.com/dmi3xizxq/image/upload/ijcdofyydyrp39salzvb	2003-01-01	00988776677	4269056519096680	cabc1a1a0a4ce4400fe2722ff8bdc2c07438dd06d3e13b6ed26ce00fb2664db8605903ca5c8b387f0f010c2ddb23baa9e8bd765cdcc6b597e351e60221b2f80bd9005e3bea89aa33f0e3b1fa8df76f9d3c24baa81a9d3d40f44bb43d0ba59236ce804e60008fa4101c18b1e510f991c9772d6beeaaa9741a6a6f23888dd33db9010001	BRONZE	0.0	2025-10-01	2025-12-01 22:12:18.445841+07	Nam	0
16	thuy nga	Bắc Ninh	http://res.cloudinary.com/dmi3xizxq/image/upload/ehfmfjqdgpw0wr8hxmdi	2003-01-01	0124895985	4813248814707429	a789a6d11c170549c255e774155be1da2db870a2bdf6b287ce87fb8275ec4d7799e920049e5ef27a154552d219b42db3ff8ffc78d97a2db73d62f1aa7f76e2177b1e94c30dc4150e5922148340bdafab0f3aa08ecd3af67df40737adf50dd69e29cad1a8def2588cf0e03063aa08340fbfcc2f0588bc05946eb4dcd1d87c347f010001	BRONZE	0.0	2025-10-01	2025-12-02 00:16:12.410628+07	Nam	0
64	kien	hà nội	http://res.cloudinary.com/dmi3xizxq/image/upload/r8vb3fbhns0kzogloflv	2025-12-01	123456789	8538071015550084	AIDNu7bp0JxT1LHyCcFuwH+Xb6q96YrC36ra3diA5Hz1z76uLnHKjP3YVrcWI3xPTB1Ams52w/LsINfvOd1Pu81n5PEbIdkhfemR2zcyddAU3zaJhmk25RgxZ1xnker2fOmN0qYByWBrm/ORnimP67zPQdsYlvpE5FRij3J+GT8NqQADAQAB	BRONZE	0.0	2025-10-01	2025-12-17 09:14:39.318304+07	Nam	0
67	Thuý Nga	Hà Nội	http://res.cloudinary.com/dmi3xizxq/image/upload/ychzydzlrsaioosgjnp5	2025-12-01	123465789	7928195238306001	AIC5VEXF/ipFygdBQaWCYPWpdzy4cBpy9Z/amggIYX+N2C4MeYjncrnTTlIT1JAsrS4arSHkAk/RAXTlWTgJGaehJbUVjXpKRQ4SySLrpL8EmwtKSGKqCz6yQuX9S4Rm3vJFy7yhvz2cP0pZbDKm6Is0hv4q+n0/+MSG88e4JzENYwADAQAB	BRONZE	0.0	2025-10-01	2025-12-18 07:46:00.135018+07	Nam	1000000000
77	Lưu đình kiên	Hà nội	http://res.cloudinary.com/dmi3xizxq/image/upload/tcvu5equfbtbq88uiij9	2025-12-01	0478277383	4111116801158439	AICpm6zstYthkkK4fUF5M0CpOf4yf3jhWU8dtHll+W2hqQCFZRcv/JG58alqO2mWPOUjhqBwVAOBvVuq8Z+YYM2x4lPBO7Sck3iFfdQe1lrWsPcVuZu2Zbwud9LWCg4vBNiihB8JhTpXeAUDBClXP42AMwErfR6sEW4zMFYsu+l9uQADAQAB	BRONZE	0.0	2025-10-01	2025-12-18 08:35:24.430917+07	Nam	0
\.


--
-- Name: order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_item_id_seq', 6, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 6, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 3, true);


--
-- Name: system_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.system_users_id_seq', 2, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 77, true);


--
-- Name: users card_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT card_unique UNIQUE (id);


--
-- Name: orders orders_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_code_key UNIQUE (code);


--
-- Name: order_item orders_item_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT orders_item_pk PRIMARY KEY (id);


--
-- Name: orders orders_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pk PRIMARY KEY (id);


--
-- Name: products products_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_code_key UNIQUE (code);


--
-- Name: products products_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pk PRIMARY KEY (id);


--
-- Name: users user_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_pk PRIMARY KEY (id);


--
-- Name: users users_card_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_card_id_key UNIQUE (card_id);


--
-- Name: users users_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phone_key UNIQUE (phone);


--
-- Name: idx_products_search_vector; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_search_vector ON public.products USING gin (search_vector);


--
-- Name: order_date_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_date_idx ON public.orders USING btree (create_at);


--
-- Name: order_item_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item_code_idx ON public.order_item USING btree (order_code);


--
-- Name: product_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_code_idx ON public.products USING btree (code);


--
-- Name: user_card_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_card_idx ON public.users USING btree (card_id);


--
-- Name: order_item order_item_order_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_order_fk FOREIGN KEY (order_code) REFERENCES public.orders(code);


--
-- Name: order_item order_item_product_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_product_fk FOREIGN KEY (product_code) REFERENCES public.products(code);


--
-- PostgreSQL database dump complete
--

\unrestrict MlErO2eeADHI92ZdsLOL5XMct23PteaevqwdCsfr4gUrJ6lbZJwpMpSTRaaDxvq

