create table system_users
(
    id       BIGINT generated BY DEFAULT AS IDENTITY,
    email    varchar(50) not null,
    password text        not null,
    role     varchar(20)
);

create table users
(
    id            BIGINT generated BY DEFAULT AS IDENTITY,
    user_name     varchar(100) not null,
    pin           varchar(255) not null,
    address       varchar(255) not null,
    image         text         not null,
    date_of_birth date         not null,
    phone         varchar(11)  not null unique,
    card_id       varchar(16)  not null unique,
    public_key    text         not null,
    balance       decimal(15, 1)
);

create table products
(
    id     bigint generated by default as identity,
    code   varchar(15)  not null unique,
    name   varchar(255) not null,
    remain integer      not null,
    price  decimal(15, 1)
);

create table orders
(
    id          bigint generated by default as identity,
    code        varchar(30) not null unique,
    user_id     bigint      not null,
    total_price decimal(15, 1),
    create_at   timestamptz DEFAULT NOW()
);

create table order_item
(
    id           bigint generated by default as identity,
    order_code   varchar(30) not null,
    product_code varchar(15) not null,
    quantity     int8        not null,
    price        decimal(15, 1)
);

alter table system_users
    add constraint sys_user_pk primary key (id);

alter table users
    add constraint user_pk primary key (id);

alter table users
    add constraint card_unique unique (id);

alter table products
    add constraint products_pk primary key (id);

alter table orders
    add constraint orders_pk primary key (id);

alter table order_item
    add constraint orders_item_pk primary key (id);

alter table orders
    add constraint orders_user_fk foreign key (user_id) references users (id);

alter table order_item
    add constraint order_item_order_fk foreign key (order_code) references orders (code);

alter table order_item
    add constraint order_item_product_fk foreign key (product_code) references products (code);

create index if not exists product_code_idx on products (code);

create index if not exists order_date_idx on orders (create_at);

create index if not exists order_item_code_idx on order_item (order_code);

create index if not exists user_card_idx on users (card_id);






